// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonsterOfTheWeek.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MonsterOfTheWeek.Api.Data.Migrations
{
    [DbContext(typeof(MotwDbContext))]
    [Migration("20260719163240_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Bystander", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BystanderTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("bystander_type_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("MysteryId")
                        .HasColumnType("uuid")
                        .HasColumnName("mystery_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("BystanderTypeId");

                    b.HasIndex("MysteryId");

                    b.ToTable("bystanders", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.BystanderCustomMove", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BystanderId")
                        .HasColumnType("uuid")
                        .HasColumnName("bystander_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("BystanderId");

                    b.ToTable("bystander_custom_moves", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.BystanderType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("bystander_types", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Countdown", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Day")
                        .HasColumnType("text")
                        .HasColumnName("day");

                    b.Property<string>("Dusk")
                        .HasColumnType("text")
                        .HasColumnName("dusk");

                    b.Property<string>("Midnight")
                        .HasColumnType("text")
                        .HasColumnName("midnight");

                    b.Property<Guid>("MysteryId")
                        .HasColumnType("uuid")
                        .HasColumnName("mystery_id");

                    b.Property<string>("Nightfall")
                        .HasColumnType("text")
                        .HasColumnName("nightfall");

                    b.Property<string>("Shadows")
                        .HasColumnType("text")
                        .HasColumnName("shadows");

                    b.Property<string>("Sunset")
                        .HasColumnType("text")
                        .HasColumnName("sunset");

                    b.HasKey("Id");

                    b.HasIndex("MysteryId")
                        .IsUnique();

                    b.ToTable("countdowns", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("LocationTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_type_id");

                    b.Property<Guid>("MysteryId")
                        .HasColumnType("uuid")
                        .HasColumnName("mystery_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("LocationTypeId");

                    b.HasIndex("MysteryId");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.LocationCustomMove", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("location_custom_moves", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.LocationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("location_types", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("minion_types", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Monster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("HarmCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("harm_capacity");

                    b.Property<Guid?>("MinionTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("minion_type_id");

                    b.Property<Guid?>("MonsterTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_type_id");

                    b.Property<Guid>("MysteryId")
                        .HasColumnType("uuid")
                        .HasColumnName("mystery_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MinionTypeId");

                    b.HasIndex("MonsterTypeId");

                    b.HasIndex("MysteryId");

                    b.ToTable("monsters", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterArmor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("HarmSoak")
                        .HasColumnType("integer")
                        .HasColumnName("harm_soak");

                    b.Property<bool>("IsMagical")
                        .HasColumnType("boolean")
                        .HasColumnName("is_magical");

                    b.Property<Guid>("MonsterId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MonsterId");

                    b.ToTable("monster_armors", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterAttack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Harm")
                        .HasColumnType("integer")
                        .HasColumnName("harm");

                    b.Property<Guid>("MonsterId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MonsterId");

                    b.ToTable("monster_attacks", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterAttackWeaponTag", b =>
                {
                    b.Property<Guid>("MonsterAttackId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_attack_id");

                    b.Property<Guid>("WeaponTagId")
                        .HasColumnType("uuid")
                        .HasColumnName("weapon_tag_id");

                    b.HasKey("MonsterAttackId", "WeaponTagId");

                    b.HasIndex("WeaponTagId");

                    b.ToTable("monster_attack_weapon_tags", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterCustomMove", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("MonsterId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MonsterId");

                    b.ToTable("monster_custom_moves", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterPower", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("MonsterId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MonsterId");

                    b.ToTable("monster_powers", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("monster_types", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterWeakness", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("MonsterId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MonsterId");

                    b.ToTable("monster_weaknesses", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Mystery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Concept")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("concept");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Hook")
                        .HasColumnType("text")
                        .HasColumnName("hook");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Overview")
                        .HasColumnType("text")
                        .HasColumnName("overview");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("mysteries", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MysteryCustomMove", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("MysteryId")
                        .HasColumnType("uuid")
                        .HasColumnName("mystery_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MysteryId");

                    b.ToTable("mystery_custom_moves", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.WeaponTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("weapon_tags", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Bystander", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.BystanderType", "BystanderType")
                        .WithMany("Bystanders")
                        .HasForeignKey("BystanderTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Mystery", "Mystery")
                        .WithMany("Bystanders")
                        .HasForeignKey("MysteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BystanderType");

                    b.Navigation("Mystery");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.BystanderCustomMove", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Bystander", "Bystander")
                        .WithMany("CustomMoves")
                        .HasForeignKey("BystanderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bystander");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Countdown", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Mystery", "Mystery")
                        .WithOne("Countdown")
                        .HasForeignKey("MonsterOfTheWeek.Api.Data.Entities.Countdown", "MysteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mystery");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Location", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.LocationType", "LocationType")
                        .WithMany("Locations")
                        .HasForeignKey("LocationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Mystery", "Mystery")
                        .WithMany("Locations")
                        .HasForeignKey("MysteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocationType");

                    b.Navigation("Mystery");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.LocationCustomMove", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Location", "Location")
                        .WithMany("CustomMoves")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Monster", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.MinionType", "MinionType")
                        .WithMany("Monsters")
                        .HasForeignKey("MinionTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.MonsterType", "MonsterType")
                        .WithMany("Monsters")
                        .HasForeignKey("MonsterTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Mystery", "Mystery")
                        .WithMany("Monsters")
                        .HasForeignKey("MysteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MinionType");

                    b.Navigation("MonsterType");

                    b.Navigation("Mystery");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterArmor", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Monster", "Monster")
                        .WithMany("Armors")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterAttack", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Monster", "Monster")
                        .WithMany("Attacks")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterAttackWeaponTag", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.MonsterAttack", "MonsterAttack")
                        .WithMany("MonsterAttackWeaponTags")
                        .HasForeignKey("MonsterAttackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.WeaponTag", "WeaponTag")
                        .WithMany("MonsterAttackWeaponTags")
                        .HasForeignKey("WeaponTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonsterAttack");

                    b.Navigation("WeaponTag");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterCustomMove", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Monster", "Monster")
                        .WithMany("CustomMoves")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterPower", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Monster", "Monster")
                        .WithMany("Powers")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterWeakness", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Monster", "Monster")
                        .WithMany("Weaknesses")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MysteryCustomMove", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Mystery", "Mystery")
                        .WithMany("CustomMoves")
                        .HasForeignKey("MysteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mystery");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Bystander", b =>
                {
                    b.Navigation("CustomMoves");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.BystanderType", b =>
                {
                    b.Navigation("Bystanders");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Location", b =>
                {
                    b.Navigation("CustomMoves");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.LocationType", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionType", b =>
                {
                    b.Navigation("Monsters");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Monster", b =>
                {
                    b.Navigation("Armors");

                    b.Navigation("Attacks");

                    b.Navigation("CustomMoves");

                    b.Navigation("Powers");

                    b.Navigation("Weaknesses");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterAttack", b =>
                {
                    b.Navigation("MonsterAttackWeaponTags");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterType", b =>
                {
                    b.Navigation("Monsters");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Mystery", b =>
                {
                    b.Navigation("Bystanders");

                    b.Navigation("Countdown");

                    b.Navigation("CustomMoves");

                    b.Navigation("Locations");

                    b.Navigation("Monsters");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.WeaponTag", b =>
                {
                    b.Navigation("MonsterAttackWeaponTags");
                });
#pragma warning restore 612, 618
        }
    }
}
