// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonsterOfTheWeek.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MonsterOfTheWeek.Api.Data.Migrations
{
    [DbContext(typeof(MotwDbContext))]
    [Migration("20260831190456_AddHunter")]
    partial class AddHunter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.AdventureType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("adventure_types", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_app_users_email");

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.BasicMove", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DescriptionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.ToTable("basic_moves", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.BespokeJournal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EffectText")
                        .HasColumnType("text")
                        .HasColumnName("effect_text");

                    b.Property<Guid>("PlaybookId")
                        .HasColumnType("uuid")
                        .HasColumnName("playbook_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("PlaybookId")
                        .HasDatabaseName("idx_bespoke_journals_playbook_id");

                    b.ToTable("bespoke_journals", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.BespokeJournalField", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("JournalId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("label");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("JournalId")
                        .HasDatabaseName("idx_bespoke_journal_fields_journal_id");

                    b.ToTable("bespoke_journal_fields", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.BespokeOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DescriptionText")
                        .HasColumnType("text")
                        .HasColumnName("description_text");

                    b.Property<int?>("MaxSelect")
                        .HasColumnType("integer")
                        .HasColumnName("max_select");

                    b.Property<int?>("MinSelect")
                        .HasColumnType("integer")
                        .HasColumnName("min_select");

                    b.Property<int?>("NumericMax")
                        .HasColumnType("integer")
                        .HasColumnName("numeric_max");

                    b.Property<int?>("NumericMin")
                        .HasColumnType("integer")
                        .HasColumnName("numeric_min");

                    b.Property<Guid?>("ParentOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_option_id");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("section_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ParentOptionId")
                        .HasDatabaseName("idx_bespoke_options_parent_option_id");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("idx_bespoke_options_section_id");

                    b.ToTable("bespoke_options", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.BespokeSection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EffectText")
                        .HasColumnType("text")
                        .HasColumnName("effect_text");

                    b.Property<string>("FreeTextLabel")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("free_text_label");

                    b.Property<int?>("MaxInstances")
                        .HasColumnType("integer")
                        .HasColumnName("max_instances");

                    b.Property<int?>("MaxSelect")
                        .HasColumnType("integer")
                        .HasColumnName("max_select");

                    b.Property<int?>("MinInstances")
                        .HasColumnType("integer")
                        .HasColumnName("min_instances");

                    b.Property<int?>("MinSelect")
                        .HasColumnType("integer")
                        .HasColumnName("min_select");

                    b.Property<Guid>("PlaybookId")
                        .HasColumnType("uuid")
                        .HasColumnName("playbook_id");

                    b.Property<Guid?>("PlaybookMoveId")
                        .HasColumnType("uuid")
                        .HasColumnName("playbook_move_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("PlaybookId")
                        .HasDatabaseName("idx_bespoke_sections_playbook_id");

                    b.HasIndex("PlaybookMoveId")
                        .HasDatabaseName("idx_bespoke_sections_playbook_move_id");

                    b.ToTable("bespoke_sections", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Bystander", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BystanderTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("bystander_type_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BystanderTypeId");

                    b.ToTable("bystanders", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.BystanderCustomMove", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BystanderId")
                        .HasColumnType("uuid")
                        .HasColumnName("bystander_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("BystanderId");

                    b.ToTable("bystander_custom_moves", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.BystanderType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("bystander_types", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Countdown", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Day")
                        .HasColumnType("text")
                        .HasColumnName("day");

                    b.Property<string>("Dusk")
                        .HasColumnType("text")
                        .HasColumnName("dusk");

                    b.Property<string>("Midnight")
                        .HasColumnType("text")
                        .HasColumnName("midnight");

                    b.Property<Guid>("MysteryId")
                        .HasColumnType("uuid")
                        .HasColumnName("mystery_id");

                    b.Property<string>("Nightfall")
                        .HasColumnType("text")
                        .HasColumnName("nightfall");

                    b.Property<string>("Shadows")
                        .HasColumnType("text")
                        .HasColumnName("shadows");

                    b.Property<string>("Sunset")
                        .HasColumnType("text")
                        .HasColumnName("sunset");

                    b.HasKey("Id");

                    b.HasIndex("MysteryId")
                        .IsUnique();

                    b.ToTable("countdowns", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Hunter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("PlaybookId")
                        .HasColumnType("uuid")
                        .HasColumnName("playbook_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlaybookId")
                        .HasDatabaseName("idx_hunters_playbook_id");

                    b.ToTable("hunters", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("LocationTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LocationTypeId");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.LocationCustomMove", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("location_custom_moves", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.LocationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("location_types", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Minion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("HarmCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("harm_capacity");

                    b.Property<Guid>("MinionTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("minion_type_id");

                    b.Property<Guid>("MonsterId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MinionTypeId")
                        .HasDatabaseName("idx_minions_minion_type_id");

                    b.HasIndex("MonsterId")
                        .HasDatabaseName("idx_minions_monster_id");

                    b.ToTable("minions", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionArmor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("HarmSoak")
                        .HasColumnType("integer")
                        .HasColumnName("harm_soak");

                    b.Property<bool>("IsSpecial")
                        .HasColumnType("boolean")
                        .HasColumnName("is_special");

                    b.Property<Guid>("MinionId")
                        .HasColumnType("uuid")
                        .HasColumnName("minion_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("SpecialDescription")
                        .HasColumnType("text")
                        .HasColumnName("special_description");

                    b.HasKey("Id");

                    b.HasIndex("MinionId");

                    b.ToTable("minion_armors", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionAttack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Harm")
                        .HasColumnType("integer")
                        .HasColumnName("harm");

                    b.Property<Guid>("MinionId")
                        .HasColumnType("uuid")
                        .HasColumnName("minion_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MinionId");

                    b.ToTable("minion_attacks", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionAttackWeaponTag", b =>
                {
                    b.Property<Guid>("MinionAttackId")
                        .HasColumnType("uuid")
                        .HasColumnName("minion_attack_id");

                    b.Property<Guid>("WeaponTagId")
                        .HasColumnType("uuid")
                        .HasColumnName("weapon_tag_id");

                    b.HasKey("MinionAttackId", "WeaponTagId");

                    b.HasIndex("WeaponTagId");

                    b.ToTable("minion_attack_weapon_tags", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionCustomMove", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("MinionId")
                        .HasColumnType("uuid")
                        .HasColumnName("minion_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MinionId");

                    b.ToTable("minion_custom_moves", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionPower", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("MinionId")
                        .HasColumnType("uuid")
                        .HasColumnName("minion_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MinionId");

                    b.ToTable("minion_powers", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("minion_types", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionWeakness", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("MinionId")
                        .HasColumnType("uuid")
                        .HasColumnName("minion_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MinionId");

                    b.ToTable("minion_weaknesses", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Monster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("HarmCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("harm_capacity");

                    b.Property<Guid>("MonsterArchetypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_archetype_id");

                    b.Property<Guid>("MonsterTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MonsterArchetypeId");

                    b.HasIndex("MonsterTypeId");

                    b.ToTable("monsters", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterArchetype", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("monster_archetypes", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterArmor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("HarmSoak")
                        .HasColumnType("integer")
                        .HasColumnName("harm_soak");

                    b.Property<bool>("IsSpecial")
                        .HasColumnType("boolean")
                        .HasColumnName("is_special");

                    b.Property<Guid>("MonsterId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("SpecialDescription")
                        .HasColumnType("text")
                        .HasColumnName("special_description");

                    b.HasKey("Id");

                    b.HasIndex("MonsterId");

                    b.ToTable("monster_armors", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterAttack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Harm")
                        .HasColumnType("integer")
                        .HasColumnName("harm");

                    b.Property<Guid>("MonsterId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MonsterId");

                    b.ToTable("monster_attacks", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterAttackWeaponTag", b =>
                {
                    b.Property<Guid>("MonsterAttackId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_attack_id");

                    b.Property<Guid>("WeaponTagId")
                        .HasColumnType("uuid")
                        .HasColumnName("weapon_tag_id");

                    b.HasKey("MonsterAttackId", "WeaponTagId");

                    b.HasIndex("WeaponTagId");

                    b.ToTable("monster_attack_weapon_tags", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterCustomMove", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("MonsterId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MonsterId");

                    b.ToTable("monster_custom_moves", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterPower", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("MonsterId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MonsterId");

                    b.ToTable("monster_powers", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("monster_types", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterWeakness", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("MonsterId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MonsterId");

                    b.ToTable("monster_weaknesses", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Mystery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdventureTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("adventure_type_id");

                    b.Property<string>("Concept")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("concept");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Hook")
                        .HasColumnType("text")
                        .HasColumnName("hook");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Overview")
                        .HasColumnType("text")
                        .HasColumnName("overview");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AdventureTypeId");

                    b.ToTable("mysteries", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MysteryBystander", b =>
                {
                    b.Property<Guid>("MysteryId")
                        .HasColumnType("uuid")
                        .HasColumnName("mystery_id");

                    b.Property<Guid>("BystanderId")
                        .HasColumnType("uuid")
                        .HasColumnName("bystander_id");

                    b.HasKey("MysteryId", "BystanderId");

                    b.HasIndex("BystanderId");

                    b.ToTable("mystery_bystanders", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MysteryCustomMove", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("MysteryId")
                        .HasColumnType("uuid")
                        .HasColumnName("mystery_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MysteryId");

                    b.ToTable("mystery_custom_moves", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MysteryLocation", b =>
                {
                    b.Property<Guid>("MysteryId")
                        .HasColumnType("uuid")
                        .HasColumnName("mystery_id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.HasKey("MysteryId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("mystery_locations", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MysteryMonster", b =>
                {
                    b.Property<Guid>("MysteryId")
                        .HasColumnType("uuid")
                        .HasColumnName("mystery_id");

                    b.Property<Guid>("MonsterId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_id");

                    b.HasKey("MysteryId", "MonsterId");

                    b.HasIndex("MonsterId");

                    b.ToTable("mystery_monsters", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Playbook", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("ExperienceBoxCount")
                        .HasColumnType("integer")
                        .HasColumnName("experience_box_count");

                    b.Property<string>("GettingStartedText")
                        .HasColumnType("text")
                        .HasColumnName("getting_started_text");

                    b.Property<int>("HarmBoxCount")
                        .HasColumnType("integer")
                        .HasColumnName("harm_box_count");

                    b.Property<int>("HarmUnstableThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("harm_unstable_threshold");

                    b.Property<string>("HistoryPromptsText")
                        .HasColumnType("text")
                        .HasColumnName("history_prompts_text");

                    b.Property<string>("IntroductionsText")
                        .HasColumnType("text")
                        .HasColumnName("introductions_text");

                    b.Property<string>("LevelingUpText")
                        .HasColumnType("text")
                        .HasColumnName("leveling_up_text");

                    b.Property<int>("LuckBoxCount")
                        .HasColumnType("integer")
                        .HasColumnName("luck_box_count");

                    b.Property<string>("LuckSpecialText")
                        .HasColumnType("text")
                        .HasColumnName("luck_special_text");

                    b.Property<int>("MoveGrantCount")
                        .HasColumnType("integer")
                        .HasColumnName("move_grant_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_playbooks_name");

                    b.ToTable("playbooks", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.PlaybookExtraTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BoxCount")
                        .HasColumnType("integer")
                        .HasColumnName("box_count");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EffectText")
                        .HasColumnType("text")
                        .HasColumnName("effect_text");

                    b.Property<string>("EndLabel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("end_label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("PlaybookId")
                        .HasColumnType("uuid")
                        .HasColumnName("playbook_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("StartLabel")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("start_label");

                    b.HasKey("Id");

                    b.HasIndex("PlaybookId")
                        .HasDatabaseName("idx_playbook_extra_tracks_playbook_id");

                    b.ToTable("playbook_extra_tracks", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.PlaybookGearCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean")
                        .HasColumnName("is_optional");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("label");

                    b.Property<int?>("PickCount")
                        .HasColumnType("integer")
                        .HasColumnName("pick_count");

                    b.Property<Guid>("PlaybookId")
                        .HasColumnType("uuid")
                        .HasColumnName("playbook_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("PlaybookId")
                        .HasDatabaseName("idx_playbook_gear_categories_playbook_id");

                    b.ToTable("playbook_gear_categories", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.PlaybookGearOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("MechanicalText")
                        .HasColumnType("text")
                        .HasColumnName("mechanical_text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("idx_playbook_gear_options_category_id");

                    b.ToTable("playbook_gear_options", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.PlaybookImprovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsAdvanced")
                        .HasColumnType("boolean")
                        .HasColumnName("is_advanced");

                    b.Property<Guid>("PlaybookId")
                        .HasColumnType("uuid")
                        .HasColumnName("playbook_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("PlaybookId")
                        .HasDatabaseName("idx_playbook_improvements_playbook_id");

                    b.ToTable("playbook_improvements", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.PlaybookLookCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowsFreeform")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_freeform");

                    b.Property<string>("GroupLabel")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("group_label");

                    b.Property<Guid>("PlaybookId")
                        .HasColumnType("uuid")
                        .HasColumnName("playbook_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("PlaybookId")
                        .HasDatabaseName("idx_playbook_look_categories_playbook_id");

                    b.ToTable("playbook_look_categories", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.PlaybookLookOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("idx_playbook_look_options_category_id");

                    b.ToTable("playbook_look_options", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.PlaybookMove", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DescriptionText")
                        .HasColumnType("text")
                        .HasColumnName("description_text");

                    b.Property<bool>("IsAdvanced")
                        .HasColumnType("boolean")
                        .HasColumnName("is_advanced");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("PlaybookId")
                        .HasColumnType("uuid")
                        .HasColumnName("playbook_id");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean")
                        .HasColumnName("required");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("PlaybookId")
                        .HasDatabaseName("idx_playbook_moves_playbook_id");

                    b.ToTable("playbook_moves", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.PlaybookStatArrayOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Charm")
                        .HasColumnType("integer")
                        .HasColumnName("charm");

                    b.Property<int>("Cool")
                        .HasColumnType("integer")
                        .HasColumnName("cool");

                    b.Property<Guid>("PlaybookId")
                        .HasColumnType("uuid")
                        .HasColumnName("playbook_id");

                    b.Property<int>("Sharp")
                        .HasColumnType("integer")
                        .HasColumnName("sharp");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("Tough")
                        .HasColumnType("integer")
                        .HasColumnName("tough");

                    b.Property<int>("Weird")
                        .HasColumnType("integer")
                        .HasColumnName("weird");

                    b.HasKey("Id");

                    b.HasIndex("PlaybookId")
                        .HasDatabaseName("idx_playbook_stat_array_options_playbook_id");

                    b.ToTable("playbook_stat_array_options", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.WeaponTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("weapon_tags", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.BespokeJournal", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Playbook", "Playbook")
                        .WithMany("BespokeJournals")
                        .HasForeignKey("PlaybookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playbook");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.BespokeJournalField", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.BespokeJournal", "Journal")
                        .WithMany("Fields")
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journal");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.BespokeOption", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.BespokeOption", "ParentOption")
                        .WithMany("ChildOptions")
                        .HasForeignKey("ParentOptionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.BespokeSection", "Section")
                        .WithMany("Options")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentOption");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.BespokeSection", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Playbook", "Playbook")
                        .WithMany("BespokeSections")
                        .HasForeignKey("PlaybookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.PlaybookMove", "PlaybookMove")
                        .WithMany("BespokeSections")
                        .HasForeignKey("PlaybookMoveId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Playbook");

                    b.Navigation("PlaybookMove");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Bystander", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.BystanderType", "BystanderType")
                        .WithMany("Bystanders")
                        .HasForeignKey("BystanderTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BystanderType");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.BystanderCustomMove", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Bystander", "Bystander")
                        .WithMany("CustomMoves")
                        .HasForeignKey("BystanderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bystander");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Countdown", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Mystery", "Mystery")
                        .WithOne("Countdown")
                        .HasForeignKey("MonsterOfTheWeek.Api.Data.Entities.Countdown", "MysteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mystery");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Hunter", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Playbook", "Playbook")
                        .WithMany()
                        .HasForeignKey("PlaybookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Playbook");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Location", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.LocationType", "LocationType")
                        .WithMany("Locations")
                        .HasForeignKey("LocationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocationType");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.LocationCustomMove", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Location", "Location")
                        .WithMany("CustomMoves")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Minion", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.MinionType", "MinionType")
                        .WithMany("Minions")
                        .HasForeignKey("MinionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Monster", "Monster")
                        .WithMany("Minions")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MinionType");

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionArmor", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Minion", "Minion")
                        .WithMany("Armors")
                        .HasForeignKey("MinionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Minion");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionAttack", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Minion", "Minion")
                        .WithMany("Attacks")
                        .HasForeignKey("MinionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Minion");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionAttackWeaponTag", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.MinionAttack", "MinionAttack")
                        .WithMany("MinionAttackWeaponTags")
                        .HasForeignKey("MinionAttackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.WeaponTag", "WeaponTag")
                        .WithMany("MinionAttackWeaponTags")
                        .HasForeignKey("WeaponTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MinionAttack");

                    b.Navigation("WeaponTag");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionCustomMove", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Minion", "Minion")
                        .WithMany("CustomMoves")
                        .HasForeignKey("MinionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Minion");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionPower", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Minion", "Minion")
                        .WithMany("Powers")
                        .HasForeignKey("MinionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Minion");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionWeakness", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Minion", "Minion")
                        .WithMany("Weaknesses")
                        .HasForeignKey("MinionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Minion");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Monster", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.MonsterArchetype", "MonsterArchetype")
                        .WithMany("Monsters")
                        .HasForeignKey("MonsterArchetypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.MonsterType", "MonsterType")
                        .WithMany("Monsters")
                        .HasForeignKey("MonsterTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonsterArchetype");

                    b.Navigation("MonsterType");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterArmor", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Monster", "Monster")
                        .WithMany("Armors")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterAttack", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Monster", "Monster")
                        .WithMany("Attacks")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterAttackWeaponTag", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.MonsterAttack", "MonsterAttack")
                        .WithMany("MonsterAttackWeaponTags")
                        .HasForeignKey("MonsterAttackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.WeaponTag", "WeaponTag")
                        .WithMany("MonsterAttackWeaponTags")
                        .HasForeignKey("WeaponTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonsterAttack");

                    b.Navigation("WeaponTag");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterCustomMove", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Monster", "Monster")
                        .WithMany("CustomMoves")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterPower", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Monster", "Monster")
                        .WithMany("Powers")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterWeakness", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Monster", "Monster")
                        .WithMany("Weaknesses")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Mystery", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.AdventureType", "AdventureType")
                        .WithMany("Mysteries")
                        .HasForeignKey("AdventureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdventureType");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MysteryBystander", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Bystander", "Bystander")
                        .WithMany("Mysteries")
                        .HasForeignKey("BystanderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Mystery", "Mystery")
                        .WithMany("MysteryBystanders")
                        .HasForeignKey("MysteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bystander");

                    b.Navigation("Mystery");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MysteryCustomMove", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Mystery", "Mystery")
                        .WithMany("CustomMoves")
                        .HasForeignKey("MysteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mystery");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MysteryLocation", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Location", "Location")
                        .WithMany("Mysteries")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Mystery", "Mystery")
                        .WithMany("MysteryLocations")
                        .HasForeignKey("MysteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Mystery");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MysteryMonster", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Monster", "Monster")
                        .WithMany("Mysteries")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Mystery", "Mystery")
                        .WithMany("MysteryMonsters")
                        .HasForeignKey("MysteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");

                    b.Navigation("Mystery");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.PlaybookExtraTrack", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Playbook", "Playbook")
                        .WithMany("ExtraTracks")
                        .HasForeignKey("PlaybookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playbook");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.PlaybookGearCategory", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Playbook", "Playbook")
                        .WithMany("GearCategories")
                        .HasForeignKey("PlaybookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playbook");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.PlaybookGearOption", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.PlaybookGearCategory", "Category")
                        .WithMany("Options")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.PlaybookImprovement", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Playbook", "Playbook")
                        .WithMany("Improvements")
                        .HasForeignKey("PlaybookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playbook");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.PlaybookLookCategory", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Playbook", "Playbook")
                        .WithMany("LookCategories")
                        .HasForeignKey("PlaybookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playbook");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.PlaybookLookOption", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.PlaybookLookCategory", "Category")
                        .WithMany("Options")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.PlaybookMove", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Playbook", "Playbook")
                        .WithMany("Moves")
                        .HasForeignKey("PlaybookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playbook");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.PlaybookStatArrayOption", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Playbook", "Playbook")
                        .WithMany("StatArrayOptions")
                        .HasForeignKey("PlaybookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playbook");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.AdventureType", b =>
                {
                    b.Navigation("Mysteries");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.BespokeJournal", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.BespokeOption", b =>
                {
                    b.Navigation("ChildOptions");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.BespokeSection", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Bystander", b =>
                {
                    b.Navigation("CustomMoves");

                    b.Navigation("Mysteries");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.BystanderType", b =>
                {
                    b.Navigation("Bystanders");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Location", b =>
                {
                    b.Navigation("CustomMoves");

                    b.Navigation("Mysteries");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.LocationType", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Minion", b =>
                {
                    b.Navigation("Armors");

                    b.Navigation("Attacks");

                    b.Navigation("CustomMoves");

                    b.Navigation("Powers");

                    b.Navigation("Weaknesses");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionAttack", b =>
                {
                    b.Navigation("MinionAttackWeaponTags");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionType", b =>
                {
                    b.Navigation("Minions");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Monster", b =>
                {
                    b.Navigation("Armors");

                    b.Navigation("Attacks");

                    b.Navigation("CustomMoves");

                    b.Navigation("Minions");

                    b.Navigation("Mysteries");

                    b.Navigation("Powers");

                    b.Navigation("Weaknesses");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterArchetype", b =>
                {
                    b.Navigation("Monsters");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterAttack", b =>
                {
                    b.Navigation("MonsterAttackWeaponTags");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterType", b =>
                {
                    b.Navigation("Monsters");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Mystery", b =>
                {
                    b.Navigation("Countdown");

                    b.Navigation("CustomMoves");

                    b.Navigation("MysteryBystanders");

                    b.Navigation("MysteryLocations");

                    b.Navigation("MysteryMonsters");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Playbook", b =>
                {
                    b.Navigation("BespokeJournals");

                    b.Navigation("BespokeSections");

                    b.Navigation("ExtraTracks");

                    b.Navigation("GearCategories");

                    b.Navigation("Improvements");

                    b.Navigation("LookCategories");

                    b.Navigation("Moves");

                    b.Navigation("StatArrayOptions");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.PlaybookGearCategory", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.PlaybookLookCategory", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.PlaybookMove", b =>
                {
                    b.Navigation("BespokeSections");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.WeaponTag", b =>
                {
                    b.Navigation("MinionAttackWeaponTags");

                    b.Navigation("MonsterAttackWeaponTags");
                });
#pragma warning restore 612, 618
        }
    }
}
