// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonsterOfTheWeek.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MonsterOfTheWeek.Api.Data.Migrations
{
    [DbContext(typeof(MotwDbContext))]
    partial class MotwDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.AdventureType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("adventure_types", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_app_users_email");

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Bystander", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BystanderTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("bystander_type_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BystanderTypeId");

                    b.ToTable("bystanders", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.BystanderCustomMove", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BystanderId")
                        .HasColumnType("uuid")
                        .HasColumnName("bystander_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("BystanderId");

                    b.ToTable("bystander_custom_moves", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.BystanderType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("bystander_types", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Countdown", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Day")
                        .HasColumnType("text")
                        .HasColumnName("day");

                    b.Property<string>("Dusk")
                        .HasColumnType("text")
                        .HasColumnName("dusk");

                    b.Property<string>("Midnight")
                        .HasColumnType("text")
                        .HasColumnName("midnight");

                    b.Property<Guid>("MysteryId")
                        .HasColumnType("uuid")
                        .HasColumnName("mystery_id");

                    b.Property<string>("Nightfall")
                        .HasColumnType("text")
                        .HasColumnName("nightfall");

                    b.Property<string>("Shadows")
                        .HasColumnType("text")
                        .HasColumnName("shadows");

                    b.Property<string>("Sunset")
                        .HasColumnType("text")
                        .HasColumnName("sunset");

                    b.HasKey("Id");

                    b.HasIndex("MysteryId")
                        .IsUnique();

                    b.ToTable("countdowns", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("LocationTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LocationTypeId");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.LocationCustomMove", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("location_custom_moves", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.LocationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("location_types", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Minion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("HarmCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("harm_capacity");

                    b.Property<Guid>("MinionTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("minion_type_id");

                    b.Property<Guid>("MonsterId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MinionTypeId")
                        .HasDatabaseName("idx_minions_minion_type_id");

                    b.HasIndex("MonsterId")
                        .HasDatabaseName("idx_minions_monster_id");

                    b.ToTable("minions", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionArmor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("HarmSoak")
                        .HasColumnType("integer")
                        .HasColumnName("harm_soak");

                    b.Property<bool>("IsSpecial")
                        .HasColumnType("boolean")
                        .HasColumnName("is_special");

                    b.Property<Guid>("MinionId")
                        .HasColumnType("uuid")
                        .HasColumnName("minion_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("SpecialDescription")
                        .HasColumnType("text")
                        .HasColumnName("special_description");

                    b.HasKey("Id");

                    b.HasIndex("MinionId");

                    b.ToTable("minion_armors", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionAttack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Harm")
                        .HasColumnType("integer")
                        .HasColumnName("harm");

                    b.Property<Guid>("MinionId")
                        .HasColumnType("uuid")
                        .HasColumnName("minion_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MinionId");

                    b.ToTable("minion_attacks", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionAttackWeaponTag", b =>
                {
                    b.Property<Guid>("MinionAttackId")
                        .HasColumnType("uuid")
                        .HasColumnName("minion_attack_id");

                    b.Property<Guid>("WeaponTagId")
                        .HasColumnType("uuid")
                        .HasColumnName("weapon_tag_id");

                    b.HasKey("MinionAttackId", "WeaponTagId");

                    b.HasIndex("WeaponTagId");

                    b.ToTable("minion_attack_weapon_tags", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionCustomMove", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("MinionId")
                        .HasColumnType("uuid")
                        .HasColumnName("minion_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MinionId");

                    b.ToTable("minion_custom_moves", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionPower", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("MinionId")
                        .HasColumnType("uuid")
                        .HasColumnName("minion_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MinionId");

                    b.ToTable("minion_powers", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("minion_types", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionWeakness", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("MinionId")
                        .HasColumnType("uuid")
                        .HasColumnName("minion_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MinionId");

                    b.ToTable("minion_weaknesses", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Monster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("HarmCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("harm_capacity");

                    b.Property<Guid>("MonsterArchetypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_archetype_id");

                    b.Property<Guid>("MonsterTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MonsterArchetypeId");

                    b.HasIndex("MonsterTypeId");

                    b.ToTable("monsters", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterArchetype", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("monster_archetypes", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterArmor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("HarmSoak")
                        .HasColumnType("integer")
                        .HasColumnName("harm_soak");

                    b.Property<bool>("IsSpecial")
                        .HasColumnType("boolean")
                        .HasColumnName("is_special");

                    b.Property<Guid>("MonsterId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("SpecialDescription")
                        .HasColumnType("text")
                        .HasColumnName("special_description");

                    b.HasKey("Id");

                    b.HasIndex("MonsterId");

                    b.ToTable("monster_armors", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterAttack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Harm")
                        .HasColumnType("integer")
                        .HasColumnName("harm");

                    b.Property<Guid>("MonsterId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MonsterId");

                    b.ToTable("monster_attacks", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterAttackWeaponTag", b =>
                {
                    b.Property<Guid>("MonsterAttackId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_attack_id");

                    b.Property<Guid>("WeaponTagId")
                        .HasColumnType("uuid")
                        .HasColumnName("weapon_tag_id");

                    b.HasKey("MonsterAttackId", "WeaponTagId");

                    b.HasIndex("WeaponTagId");

                    b.ToTable("monster_attack_weapon_tags", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterCustomMove", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("MonsterId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MonsterId");

                    b.ToTable("monster_custom_moves", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterPower", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("MonsterId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MonsterId");

                    b.ToTable("monster_powers", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("monster_types", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterWeakness", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("MonsterId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MonsterId");

                    b.ToTable("monster_weaknesses", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Mystery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdventureTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("adventure_type_id");

                    b.Property<string>("Concept")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("concept");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Hook")
                        .HasColumnType("text")
                        .HasColumnName("hook");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Overview")
                        .HasColumnType("text")
                        .HasColumnName("overview");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AdventureTypeId");

                    b.ToTable("mysteries", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MysteryBystander", b =>
                {
                    b.Property<Guid>("MysteryId")
                        .HasColumnType("uuid")
                        .HasColumnName("mystery_id");

                    b.Property<Guid>("BystanderId")
                        .HasColumnType("uuid")
                        .HasColumnName("bystander_id");

                    b.HasKey("MysteryId", "BystanderId");

                    b.HasIndex("BystanderId");

                    b.ToTable("mystery_bystanders", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MysteryCustomMove", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("MysteryId")
                        .HasColumnType("uuid")
                        .HasColumnName("mystery_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MysteryId");

                    b.ToTable("mystery_custom_moves", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MysteryLocation", b =>
                {
                    b.Property<Guid>("MysteryId")
                        .HasColumnType("uuid")
                        .HasColumnName("mystery_id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.HasKey("MysteryId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("mystery_locations", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MysteryMonster", b =>
                {
                    b.Property<Guid>("MysteryId")
                        .HasColumnType("uuid")
                        .HasColumnName("mystery_id");

                    b.Property<Guid>("MonsterId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_id");

                    b.HasKey("MysteryId", "MonsterId");

                    b.HasIndex("MonsterId");

                    b.ToTable("mystery_monsters", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.WeaponTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("weapon_tags", (string)null);
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Bystander", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.BystanderType", "BystanderType")
                        .WithMany("Bystanders")
                        .HasForeignKey("BystanderTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BystanderType");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.BystanderCustomMove", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Bystander", "Bystander")
                        .WithMany("CustomMoves")
                        .HasForeignKey("BystanderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bystander");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Countdown", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Mystery", "Mystery")
                        .WithOne("Countdown")
                        .HasForeignKey("MonsterOfTheWeek.Api.Data.Entities.Countdown", "MysteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mystery");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Location", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.LocationType", "LocationType")
                        .WithMany("Locations")
                        .HasForeignKey("LocationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocationType");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.LocationCustomMove", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Location", "Location")
                        .WithMany("CustomMoves")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Minion", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.MinionType", "MinionType")
                        .WithMany("Minions")
                        .HasForeignKey("MinionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Monster", "Monster")
                        .WithMany("Minions")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MinionType");

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionArmor", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Minion", "Minion")
                        .WithMany("Armors")
                        .HasForeignKey("MinionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Minion");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionAttack", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Minion", "Minion")
                        .WithMany("Attacks")
                        .HasForeignKey("MinionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Minion");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionAttackWeaponTag", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.MinionAttack", "MinionAttack")
                        .WithMany("MinionAttackWeaponTags")
                        .HasForeignKey("MinionAttackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.WeaponTag", "WeaponTag")
                        .WithMany("MinionAttackWeaponTags")
                        .HasForeignKey("WeaponTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MinionAttack");

                    b.Navigation("WeaponTag");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionCustomMove", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Minion", "Minion")
                        .WithMany("CustomMoves")
                        .HasForeignKey("MinionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Minion");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionPower", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Minion", "Minion")
                        .WithMany("Powers")
                        .HasForeignKey("MinionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Minion");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionWeakness", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Minion", "Minion")
                        .WithMany("Weaknesses")
                        .HasForeignKey("MinionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Minion");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Monster", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.MonsterArchetype", "MonsterArchetype")
                        .WithMany("Monsters")
                        .HasForeignKey("MonsterArchetypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.MonsterType", "MonsterType")
                        .WithMany("Monsters")
                        .HasForeignKey("MonsterTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonsterArchetype");

                    b.Navigation("MonsterType");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterArmor", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Monster", "Monster")
                        .WithMany("Armors")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterAttack", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Monster", "Monster")
                        .WithMany("Attacks")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterAttackWeaponTag", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.MonsterAttack", "MonsterAttack")
                        .WithMany("MonsterAttackWeaponTags")
                        .HasForeignKey("MonsterAttackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.WeaponTag", "WeaponTag")
                        .WithMany("MonsterAttackWeaponTags")
                        .HasForeignKey("WeaponTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonsterAttack");

                    b.Navigation("WeaponTag");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterCustomMove", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Monster", "Monster")
                        .WithMany("CustomMoves")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterPower", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Monster", "Monster")
                        .WithMany("Powers")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterWeakness", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Monster", "Monster")
                        .WithMany("Weaknesses")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Mystery", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.AdventureType", "AdventureType")
                        .WithMany("Mysteries")
                        .HasForeignKey("AdventureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdventureType");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MysteryBystander", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Bystander", "Bystander")
                        .WithMany("Mysteries")
                        .HasForeignKey("BystanderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Mystery", "Mystery")
                        .WithMany("MysteryBystanders")
                        .HasForeignKey("MysteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bystander");

                    b.Navigation("Mystery");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MysteryCustomMove", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Mystery", "Mystery")
                        .WithMany("CustomMoves")
                        .HasForeignKey("MysteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mystery");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MysteryLocation", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Location", "Location")
                        .WithMany("Mysteries")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Mystery", "Mystery")
                        .WithMany("MysteryLocations")
                        .HasForeignKey("MysteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Mystery");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MysteryMonster", b =>
                {
                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Monster", "Monster")
                        .WithMany("Mysteries")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonsterOfTheWeek.Api.Data.Entities.Mystery", "Mystery")
                        .WithMany("MysteryMonsters")
                        .HasForeignKey("MysteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");

                    b.Navigation("Mystery");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.AdventureType", b =>
                {
                    b.Navigation("Mysteries");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Bystander", b =>
                {
                    b.Navigation("CustomMoves");

                    b.Navigation("Mysteries");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.BystanderType", b =>
                {
                    b.Navigation("Bystanders");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Location", b =>
                {
                    b.Navigation("CustomMoves");

                    b.Navigation("Mysteries");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.LocationType", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Minion", b =>
                {
                    b.Navigation("Armors");

                    b.Navigation("Attacks");

                    b.Navigation("CustomMoves");

                    b.Navigation("Powers");

                    b.Navigation("Weaknesses");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionAttack", b =>
                {
                    b.Navigation("MinionAttackWeaponTags");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MinionType", b =>
                {
                    b.Navigation("Minions");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Monster", b =>
                {
                    b.Navigation("Armors");

                    b.Navigation("Attacks");

                    b.Navigation("CustomMoves");

                    b.Navigation("Minions");

                    b.Navigation("Mysteries");

                    b.Navigation("Powers");

                    b.Navigation("Weaknesses");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterArchetype", b =>
                {
                    b.Navigation("Monsters");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterAttack", b =>
                {
                    b.Navigation("MonsterAttackWeaponTags");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.MonsterType", b =>
                {
                    b.Navigation("Monsters");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.Mystery", b =>
                {
                    b.Navigation("Countdown");

                    b.Navigation("CustomMoves");

                    b.Navigation("MysteryBystanders");

                    b.Navigation("MysteryLocations");

                    b.Navigation("MysteryMonsters");
                });

            modelBuilder.Entity("MonsterOfTheWeek.Api.Data.Entities.WeaponTag", b =>
                {
                    b.Navigation("MinionAttackWeaponTags");

                    b.Navigation("MonsterAttackWeaponTags");
                });
#pragma warning restore 612, 618
        }
    }
}
